"""Initial migration

Revision ID: cf790886bd40
Revises: 
Create Date: 2025-08-02 16:10:53.932307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf790886bd40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_index(op.f('ix_children_is_active'), 'children', ['is_active'], unique=False)
    op.create_index(op.f('ix_children_name'), 'children', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'THERAPIST', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('child_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_availability_child_id'), 'child_availability', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_availability_day_of_week'), 'child_availability', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_child_availability_id'), 'child_availability', ['id'], unique=False)
    op.create_table('child_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_departments_child_id'), 'child_departments', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_departments_department_id'), 'child_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_child_departments_id'), 'child_departments', ['id'], unique=False)
    op.create_table('therapists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapists_department_id'), 'therapists', ['department_id'], unique=False)
    op.create_index(op.f('ix_therapists_id'), 'therapists', ['id'], unique=False)
    op.create_index(op.f('ix_therapists_is_active'), 'therapists', ['is_active'], unique=False)
    op.create_index(op.f('ix_therapists_name'), 'therapists', ['name'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_child_id'), 'sessions', ['child_id'], unique=False)
    op.create_index(op.f('ix_sessions_date'), 'sessions', ['date'], unique=False)
    op.create_index(op.f('ix_sessions_department_id'), 'sessions', ['department_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_therapist_id'), 'sessions', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_sessions_week_starting'), 'sessions', ['week_starting'], unique=False)
    op.create_table('therapist_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_availability_day_of_week'), 'therapist_availability', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_therapist_availability_id'), 'therapist_availability', ['id'], unique=False)
    op.create_index(op.f('ix_therapist_availability_is_available'), 'therapist_availability', ['is_available'], unique=False)
    op.create_index(op.f('ix_therapist_availability_therapist_id'), 'therapist_availability', ['therapist_id'], unique=False)
    op.create_table('session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logs_changed_at'), 'session_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_session_logs_changed_by'), 'session_logs', ['changed_by'], unique=False)
    op.create_index(op.f('ix_session_logs_id'), 'session_logs', ['id'], unique=False)
    op.create_index(op.f('ix_session_logs_session_id'), 'session_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_logs_session_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_changed_by'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_changed_at'), table_name='session_logs')
    op.drop_table('session_logs')
    op.drop_index(op.f('ix_therapist_availability_therapist_id'), table_name='therapist_availability')
    op.drop_index(op.f('ix_therapist_availability_is_available'), table_name='therapist_availability')
    op.drop_index(op.f('ix_therapist_availability_id'), table_name='therapist_availability')
    op.drop_index(op.f('ix_therapist_availability_day_of_week'), table_name='therapist_availability')
    op.drop_table('therapist_availability')
    op.drop_index(op.f('ix_sessions_week_starting'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_therapist_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_department_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_date'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_child_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_therapists_name'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_is_active'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_id'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_department_id'), table_name='therapists')
    op.drop_table('therapists')
    op.drop_index(op.f('ix_child_departments_id'), table_name='child_departments')
    op.drop_index(op.f('ix_child_departments_department_id'), table_name='child_departments')
    op.drop_index(op.f('ix_child_departments_child_id'), table_name='child_departments')
    op.drop_table('child_departments')
    op.drop_index(op.f('ix_child_availability_id'), table_name='child_availability')
    op.drop_index(op.f('ix_child_availability_day_of_week'), table_name='child_availability')
    op.drop_index(op.f('ix_child_availability_child_id'), table_name='child_availability')
    op.drop_table('child_availability')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_children_name'), table_name='children')
    op.drop_index(op.f('ix_children_is_active'), table_name='children')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
